/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caixa.eletrônico.poo;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;


public class GUI extends javax.swing.JFrame {
    private static int nextState = 0;
    private static String entry = "";
    private static float  accountBalance = 0;
    private static String accountNumber = "";
    private static String accountPin = "";
    private static String accountName = "";
    private static int State = 0;
    private static String[] ConsoleText = new String[10];
    private static String ConsoleActualText = "WELCOME!\n\nEnter your credentials:\n  -Account number: ";
    private static String nextStateText;
    private static int DepositCursor = 2;
    private static float depositAmount;
    private long start;
    private long finish;
    
    /**
     * Creates new form GUICashMachine
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        Button5 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        ButtonErase = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonDeposit = new javax.swing.JButton();
        ButtonTake = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Console = new javax.swing.JTextArea();
        ButtonEnter1 = new javax.swing.JButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        ButtonErase.setText("DEL");
        ButtonErase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEraseActionPerformed(evt);
            }
        });

        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });

        ButtonDeposit.setText("Insert deposit");
        ButtonDeposit.setEnabled(false);
        ButtonDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDepositActionPerformed(evt);
            }
        });

        ButtonTake.setText("Take Cash");
        ButtonTake.setEnabled(false);
        ButtonTake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTakeActionPerformed(evt);
            }
        });

        Console.setEditable(false);
        Console.setBackground(new java.awt.Color(0, 0, 0));
        Console.setColumns(20);
        Console.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Console.setForeground(new java.awt.Color(51, 102, 0));
        Console.setLineWrap(true);
        Console.setRows(5);
        Console.setText("WELCOME!\n\nEnter your credentials:\n  -Account number:\n");
        jScrollPane1.setViewportView(Console);

        ButtonEnter1.setText("GO");
        ButtonEnter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnter1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ButtonErase, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ButtonEnter1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonTake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ButtonTake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonErase, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonEnter1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ButtonDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        AtualizeConsole("8");
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        AtualizeConsole("0");
    }//GEN-LAST:event_Button0ActionPerformed

    private void ButtonEraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEraseActionPerformed
        if(GUI.entry != null){
            if(GUI.State == 3){
                String replaceFirst = GUI.entry.replaceFirst(",", ".");
                GUI.entry = replaceFirst;
                float actual = Float.parseFloat(GUI.entry);
                actual /= 10;
                DecimalFormat df = new DecimalFormat("00000.00");
                GUI.entry = df.format(actual);
                AtualizeConsole();
            }else{
                String tmp = "";

                for(int i = 0; i < GUI.entry.length() - 1; i++)
                    tmp += GUI.entry.charAt(i);

                GUI.entry = tmp;
                AtualizeConsole();
            }
        }
    }//GEN-LAST:event_ButtonEraseActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        AtualizeConsole("1");
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        AtualizeConsole("2");
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        AtualizeConsole("3");
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        AtualizeConsole("4");
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        AtualizeConsole("5");
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        AtualizeConsole("6");
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        AtualizeConsole("7");
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        AtualizeConsole("9");
    }//GEN-LAST:event_Button9ActionPerformed

    private void ButtonEnter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnter1ActionPerformed
        //GUARDAR TODOS OS ESTADOS EM UM VETOR DE STRING
        //POLIMORFISMO NA FUNÇÃO DE ATUALIZAR A SCREE
        switch(State){
            case 0:
                if(Controller.verifyAccountNumber() == true){
                    State++;
                    GUI.accountNumber = entry;
                    GUI.entry = "";
                    AtualizeConsoleText();
                    GUI.ConsoleActualText = GUI.ConsoleText[1];
                    AtualizeConsole();
                }else{
                    JOptionPane.showMessageDialog(this, "Incorrect account number!");
                }
                break;

            case 1:
                if(Controller.verifyAccountPin(entry) == true){
                   GUI.State = 2;
                   GUI.accountPin  = entry;
                   GUI.entry = "";
                   Controller.Transiction.accountNumber = GUI.accountNumber;
                   GUI.ConsoleActualText = GUI.ConsoleText[2];
                   AtualizeConsole();
                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect Pin Code for current account number!");
                    GUI.State = 0;
                    GUI.entry = "";
                    GUI.accountNumber = "";
                    GUI.ConsoleActualText = GUI.ConsoleText[0];
                    AtualizeConsole();
                }
            case 2:
                switch(entry){
                    case "1":
                        GUI.entry = "";
                        GUI.State = 10;
                        GUI.ConsoleActualText = GUI.ConsoleText[3];
                        GUI.nextState = 2;
                        AtualizeConsole();
                        break;

                    case "2":
                        GUI.entry = "";
                        GUI.State = 4;
                        GUI.ConsoleActualText = GUI.ConsoleText[4];
                        AtualizeConsole();
                        break;
                    case "3":
                        GUI.entry = "00000,00";
                        GUI.State = 3;
                        GUI.ConsoleActualText = GUI.ConsoleText[6];
                        AtualizeConsole();
                        break;
                        
                    case "4":
                        GUI.nextState = 0;
                        GUI.entry = "";
                        GUI.State = 10;
                        GUI.ConsoleActualText = "Thanks for use ATM!\n\n\n\nPress GO to exit.";
                        AtualizeConsole();
                        break;
                }
                break;
            case 3:
                String replaceFirst = GUI.entry.replaceFirst(",", ".");
                GUI.entry = replaceFirst;
                depositAmount = Float.parseFloat(GUI.entry);
                GUI.State = 6;
                GUI.ConsoleActualText = GUI.ConsoleText[7];
                GUI.entry = "";
                ButtonDeposit.setEnabled(true);
                AtualizeConsole();
                start = System.currentTimeMillis();
                break;

            case 4:
                float AmountTmp = 0;
                switch(entry){
                    case "1": AmountTmp = 20; break;
                    case "2": AmountTmp = 40; break;
                    case "3": AmountTmp = 60; break;
                    case "4": AmountTmp = 100; break;
                    case "5": AmountTmp = 200; break;

                    default:
                        GUI.entry = "";
                        GUI.State = 2;
                        GUI.ConsoleActualText = GUI.ConsoleText[2];
                        AtualizeConsole();
                        break;
                }

                if(GUI.State != 2){
                    Controller.WithDraw.setAmount(AmountTmp);

                    if(Controller.WithDraw.execute() == true){
                        GUI.entry = "";
                        GUI.State = 5;
                        GUI.ConsoleActualText = GUI.ConsoleText[5];
                        ButtonTake.setEnabled(true);
                        AtualizeConsole();
                    } else {
                        GUI.nextState = 4;
                        GUI.entry = "";
                        GUI.State = 10;
                        GUI.ConsoleActualText = "Limit exceeded!\n\n\n\n\n\nPress Go to back.";
                        AtualizeConsole();
                    }
                }
                break;
            
            case 5:
                break;
            case 6:
                break;
                
            case 10:
                GUI.State = GUI.nextState;
                GUI.ConsoleActualText = GUI.ConsoleText[GUI.nextState];
                AtualizeConsole();
                break;
        }
    }//GEN-LAST:event_ButtonEnter1ActionPerformed

    private void ButtonTakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTakeActionPerformed
        JOptionPane.showMessageDialog(this, "Cash taked from Dispenser");
        ButtonTake.setEnabled(false);
        ConsoleActualText = ConsoleText[2];
        GUI.State = 2;
        AtualizeConsole();
    }//GEN-LAST:event_ButtonTakeActionPerformed

    private void ButtonDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDepositActionPerformed
        finish = System.currentTimeMillis();
        long total = (finish - start)/1000;
        if(total < 60){
            GUI.nextState = 2;
            GUI.entry = "";
            GUI.State = 10;
            GUI.ConsoleActualText = "Transaction sucess!\n\n\n\n\n\nPress Go to back.";
            Controller.Deposit.setAmount(depositAmount);
            Controller.Deposit.execute();
            AtualizeConsole();
        } else {
            GUI.nextState = 2;
            GUI.entry = "";
            GUI.State = 10;
            GUI.ConsoleActualText = "Transaction canceled due to inactivity!\n\n\n\n\n\nPress Go to back.";
            AtualizeConsole();
        }
        ButtonDeposit.setEnabled(false);
    }//GEN-LAST:event_ButtonDepositActionPerformed

    public void AtualizeConsoleText(){
        for(User usr : DataBase.UserDataBase){
            if(usr.GetAccountNumber().equals(GUI.accountNumber)){
                GUI.accountBalance = usr.GetAccountBalance();
            }
        }
        ConsoleText[0] = "WELCOME!\n\nEnter your credentials:\n  -Account number: ";
        ConsoleText[1] = "WELCOME!\n\nEnter your credentials:\n  -Account number: " + GUI.accountNumber + "\n  -Account Pin code: ";
        ConsoleText[2] = "WELCOME " + accountName + "\n\nMain menu:\n  1. View my balance\n  2. Withdraw cash\n  3. Deposit funds\n  4. Exit\nEnter a choice: ";
        ConsoleText[3] = "Your Account balance is: " + GUI.accountBalance + "\n\n\n\n\nPress GO to back...";
        ConsoleText[4] =    "Withdraw menu:\n"
                          + "  1- $20    2- $40\n"
                          + "  3- $60    4- $100\n"
                          + "  5- $200   6- Cancel Transation\n"
                          + "Choose an withdraw amount: ";
        ConsoleText[5] = "Transiction sucess!\n\n\n\nTake your Cash on dispenser";
        ConsoleText[6] = "Deposit menu:\n\n\n"
                        +"Insert a value to deposit: ";
        ConsoleText[7] = "Deposit menu:\n\n\n\nInsert your mailer on Deposit";
    }
    
    public void AtualizeConsole(String entry){
        AtualizeConsoleText();
        String tmp = GUI.ConsoleActualText;
        
        if (GUI.State == 3){
            if(GUI.entry.length() <= 8){
                String replaceFirst = GUI.entry.replaceFirst(",", ".");
                GUI.entry = replaceFirst;
                float addFloat = Float.parseFloat(entry)/100f;
                float actual = Float.parseFloat(GUI.entry)*10f + addFloat;
                DecimalFormat df = new DecimalFormat("00000.00");
                GUI.entry = df.format(actual);
            }
        }else
            GUI.entry += entry;
        
        if(GUI.State != 10 && GUI.State != 5)
            tmp += GUI.entry;
        Console.setText(tmp);
    }
    
    public void AtualizeConsole(){
        AtualizeConsoleText();
        String tmp = GUI.ConsoleActualText;
        if(GUI.State != 10 && GUI.State != 5)
            tmp += entry;
        Console.setText(tmp);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonDeposit;
    private javax.swing.JButton ButtonEnter1;
    private javax.swing.JButton ButtonErase;
    private javax.swing.JButton ButtonTake;
    private javax.swing.JTextArea Console;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
